### ISSUE TITLE
undefined local variable or method "hostname"

### ISSUE THREAD

**Issue by willjasen** [willjasen/red5000#1]
Introduced with 16c999e8c71134401a78d4d46435517b2271d6ac
Method within the model needed for scheduling

**Comment by willjasen** [comment]
This is now fixed.
